import theme from "../../themes/index";
import themes from "../../theme/index";
import { StyleSheet, Dimensions, Platform, StatusBar } from "react-native";
import {
  responsiveFontSize,
  responsiveHeight,
  responsiveWidth,
} from "react-native-responsive-dimensions";

const windowHeight = Dimensions.get("window").height;
const STATUSBAR_HEIGHT = StatusBar.currentHeight;
const APPBAR_HEIGHT = Platform.OS === "ios" ? 44 : 56;

const styles = StyleSheet.create({
  Container: {
    flex: 1,
    backgroundColor: themes.colors.containerBackground,
  },
  Status: {
    backgroundColor: themes.colors.primary,
  },

  ArrowBack: {
    height: 24,
    width: 24,
  },
  BackButton: {
    height: 30,
    width: 30,
    left: 15,
  },
  HeaderTitle: {
    color: "#fff",
    lineHeight: 19.36,
    fontSize: responsiveFontSize(2),
    left: 30,
    fontFamily: "Inter-Bold",
  },
  Body: {
    width: "90%",
    alignSelf: "center",
  },
  ContinueButton: {
    backgroundColor: themes.colors.primary,
    borderRadius: 4,
    height: responsiveHeight(6),
    justifyContent: "center",
    marginVertical: 25,
    width: "100%",
    alignSelf: "center",
  },
  ContinueButtonText: {
    alignSelf: "center",
    color: "#fff",
    lineHeight: 20,
    fontSize: responsiveFontSize(2),
    fontFamily: "Inter-Regular",
  },
  UploadModalButton: {
    backgroundColor: themes.colors.primary,
    borderRadius: 4,
    height: responsiveHeight(6),
    justifyContent: "center",
    width: "90%",
    alignSelf: "center",
    position: "absolute",
    bottom: 20,
  },
  ModelContinueButton: {
    backgroundColor: "#A6A6A6",
    borderRadius: 4,
    height: responsiveHeight(6),
    justifyContent: "center",
    marginBottom: 30,
    bottom: 20,
    width: "85%",
    alignSelf: "center",
    position: "absolute",
  },
  ModelContinueButtonText: {
    alignSelf: "center",
    color: themes.colors.primary,
    lineHeight: 20,
    fontSize: 16,
  },
  ModelFeatureButton: {
    backgroundColor: "#A6A6A6",
    borderRadius: 4,
    height: responsiveHeight(6),
    justifyContent: "center",
    width: "85%",
    alignSelf: "center",
    marginBottom: 20,
    marginTop: 20,
  },
  Input: {
    // borderWidth: 1,
    // borderColor: theme.colors.primary,
    width: "100%",
    borderRadius: 6,
    alignItems: "center",
    flexDirection: "row",
    color: themes.colors.textColor,
    paddingHorizontal: 16,
    fontFamily: "Inter-Regular",
    backgroundColor: "white",
    elevation: 3,
  },
  BodyTitle: {
    fontSize: responsiveFontSize(2),
    lineHeight: 19,

    fontFamily: "Inter-Bold",
    color: themes.colors.textColor,
  },
  CountText: {
    color: "grey",
    lineHeight: 19,
    fontSize: 12,
    fontFamily: "Inter-Regular",
  },
  DescriptionInput: {
    borderWidth: 1,
    borderColor: themes.colors.primary,
    width: "100%",
    marginTop: 5,
    borderRadius: 4,
    flexDirection: "row",
    fontSize: 16,
    lineHeight: 32,
    padding: 10,
    height: 48,
  },
  photoEmptyContainer: {
    // borderWidth: 1,
    // borderColor: theme.colors.primary,
    width: "100%",
    marginTop: 5,
    height: responsiveHeight(12),
    borderRadius: 6,
    backgroundColor: themes.colors.enableField,
  },
  photoContainer: {
    // borderWidth: 1,
    // borderColor: theme.colors.primary,
    width: "100%",
    marginTop: 5,
    height: responsiveHeight(12),
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 10,
    borderRadius: 6,
    backgroundColor: themes.colors.enableField,
  },
  photoBox: {
    width: "100%",
    height: "100%",
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
    // borderWidth: 1,
    // borderColor: theme.colors.primary,
  },
  photoBoxImage: {
    width: "80%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  image: {
    width: "100%",
    height: "100%",
    borderRadius: 5,
    borderWidth: 0.5,
    borderColor: themes.colors.placeholder,
    elevation: 5,
  },
  crossBox: {
    width: 16,
    height: 16,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: themes.colors.primary,
    backgroundColor: "white",
  },
  photoSeparatorLine: {
    width: 0.5,
    height: "95%",
    backgroundColor: themes.colors.placeholder,
  },
  BodyTitleLeft: {
    fontSize: responsiveFontSize(2),
    lineHeight: 19,
    marginTop: 20,
    width: "52%",
    fontFamily: "Inter-Bold",
    color: themes.colors.textColor,
  },
  BodyTitleRight: {
    fontSize: responsiveFontSize(2),
    lineHeight: 19,
    fontFamily: "Inter-Bold",
    marginTop: 20,
    width: "48%",
    color: themes.colors.textColor,
  },
  InputLeft: {
    borderWidth: 1,
    borderColor: themes.colors.primary,
    width: "60%",
    marginTop: 10,
    height: responsiveHeight(6),
    borderRadius: 4,
    alignItems: "center",
    flexDirection: "row",
    fontSize: 16,
  },
  InputRight: {
    borderWidth: 1,
    borderColor: themes.colors.primary,
    width: "30%",
    marginTop: 10,
    height: responsiveHeight(6),
    borderRadius: 4,
    alignItems: "center",
    flexDirection: "row",
    fontSize: 16,
  },
  DropDown: {
    // borderWidth: 0.5,
    // borderColor: theme.colors.placeholder,
    width: "48%",
    height: responsiveHeight(6),
    borderRadius: 6,
    justifyContent: "center",
    overflow: "hidden",
    backgroundColor: themes.colors.enableField,
  },
  DropDownRight: {
    // borderWidth: 0.5,
    // borderColor: theme.colors.placeholder,
    width: "48%",
    height: responsiveHeight(6),
    borderRadius: 6,
    justifyContent: "center",
    overflow: "hidden",
    position: "absolute",
    right: 0,
    backgroundColor: themes.colors.enableField,
  },
  DropDownModal: {
    // borderWidth: 1,
    // borderColor: theme.colors.primary,
    width: "100%",
    height: responsiveHeight(6),
    borderRadius: 6,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 10,
    overflow: "hidden",
    backgroundColor: themes.colors.enableField,
  },

  CountryLogo: {
    height: 25,
    width: 25,
    left: 10,
  },
  ModalBody: {
    backgroundColor: "white",
    width: "90%",
    alignSelf: "center",
    borderRadius: 12,
  },
  ModalHeader: {
    alignSelf: "center",
    fontSize: responsiveFontSize(3),
    color: "#fff",
  },
  ModalSplit: {
    borderBottomWidth: 1,
    borderBottomColor: "#5299D3",
    width: "100%",
    height: 20,
  },
  ModalView: {
    flexDirection: "row",
    width: "85%",
    alignSelf: "center",
    marginTop: 10,
  },
  ChargesText: {
    fontSize: 16,
    lineHeight: 19,
    width: "50%",
    borderRightColor: "#000",
    borderRightWidth: 1,
    fontFamily: "Inter-Bold",
  },
  AmountText: {
    fontSize: 16,
    lineHeight: 19,
    width: 50,
    alignSelf: "center",
    height: responsiveHeight(6),
    color: "#000",
    fontFamily: "Inter-Regular",
  },
  CurrencyText: {
    fontFamily: "Inter-Bold",
    color: "#000",
  },
  CNICModal: {
    backgroundColor: "#fff",
    width: "95%",
    alignSelf: "center",
  },
  CNICModalHeader: {
    height: 90,
    backgroundColor: themes.colors.primary,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  CNICModalHeaderText: {
    color: "#fff",
    fontSize: responsiveFontSize(2),
    alignSelf: "center",
    width: "90%",
    fontFamily: "Inter-Regular",
    textAlign: "center",
  },
  BookText: {
    left: 20,
    fontSize: responsiveFontSize(2),
    width: "75%",
    fontFamily: "Inter-Regular",
  },
  ModalCLoseButton: {
    width: "15%",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
  },
  ModalCNICImage: {
    justifyContent: "center",
    marginTop: 30,
    width: "95%",
    alignSelf: "center",
  },
  BookModal: {
    backgroundColor: "#fff",
    height: 410,
    width: "95%",
    alignSelf: "center",
  },
  BookModalHeader: {
    height: 64,
    backgroundColor: themes.colors.primary,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  BookModalHeaderText: {
    color: "#fff",
    fontSize: 16,
    alignSelf: "center",
  },
  BookCLoseButton: {
    position: "absolute",
    right: 10,
  },
  UploadPhotosDisabled: {
    backgroundColor: "#A6A6A6",
    borderRadius: 4,
    height: responsiveHeight(6),
    justifyContent: "center",
    bottom: 20,
    width: "90%",
    alignSelf: "center",
    position: "absolute",
  },
  UploadDisableButtonText: {
    alignSelf: "center",
    color: "#fff",
    lineHeight: 20,
    fontSize: 16,
    fontFamily: "Inter-Regular",
  },
  VideoPlayer: {
    height: 200,
    width: "95%",
    alignSelf: "center",
    backgroundColor: "black",
  },
  SkipButton: {
    position: "absolute",
    backgroundColor: "grey",
    opacity: 0.6,
    color: "#fff",
    alignSelf: "flex-end",
    right: 7,
    bottom: 0,
    padding: 5,
    flexDirection: "row",
    alignItems: "center",
    height: 30,
  },
  UploadView: {
    height: 200,
    width: "95%",
    alignSelf: "center",
    backgroundColor: themes.colors.primary,
    justifyContent: "center",
    alignItems: "center",
  },
  ErrorMessage: {
    color: "red",
    fontSize: responsiveFontSize(1.2),
    fontFamily: "Inter-Regular",
  },
  Features: {
    color: "#000",
    padding: 5,
    fontFamily: "Inter-Regular",
    fontSize: responsiveFontSize(1.8),
  },
  AddedFeatures: {
    color: "#fff",
    padding: 5,
    fontFamily: "Inter-Regular",
    fontSize: responsiveFontSize(1.8),
  },
  FeaturesView: {
    borderColor: themes.colors.placeholder,
    borderWidth: 1,
    borderRadius: 20,
    marginRight: 10,
    marginTop: 10,
    paddingHorizontal: 5,
    backgroundColor: "white",
  },
  AddedFeaturesView: {
    borderColor: themes.colors.placeholder,
    borderWidth: 1,
    marginRight: 10,
    marginTop: 10,
    paddingHorizontal: 5,
    backgroundColor: "#FDB349",

    borderRadius: 20,
  },
  EmailInput: {
    borderWidth: 1,
    borderColor: themes.colors.primary,
    width: "100%",
    height: responsiveHeight(6),
    borderRadius: 4,
    alignItems: "center",
    flexDirection: "row",
    marginTop: 5,
  },

  DeleteImage: {
    backgroundColor: themes.colors.primary,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 30,
    height: 30,
    width: 30,
    position: "absolute",
    alignSelf: "flex-end",
    top: 0,
    right: 10,
  },
  DropDownitemStyle: {
    padding: 10,
    marginTop: 2,
    // backgroundColor: theme.colors.primary,
    backgroundColor: "white",
    borderColor: themes.colors.primary,
    borderBottomWidth: 0.8,
  },
  DropDownitemTextStyle: {
    // color: 'white',
    color: themes.colors.primary,
    fontWeight: "bold",
    fontSize: responsiveFontSize(1.8),
  },
  DropDownitemsContainerStyle: {
    maxHeight: responsiveHeight(24),
    borderColor: themes.colors.primary,
    borderLeftWidth: 0.8,
    borderRightWidth: 0.8,
    borderBottomWidth: 0.8,
    borderTopWidth: 0.8,
    top: 4,
    elevation: 0,
  },
  DropDowntextInputProps: {
    padding: 12,
    borderWidth: 1,
    borderColor: themes.colors.primary,
    borderRadius: 4,
    color: "black",
    fontFamily: "Inter-Regular",
    fontSize: responsiveFontSize(1.8),
  },

  modalselectorCustomListText: {
    color: themes.colors.primary_light,
    textAlign: "center",
    fontFamily: "Inter-Bold",
    textTransform: "capitalize",
  },
  modalselectoroverlayStyle: {
    flex: 1,
    padding: "10%",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.8)",
  },
  modalselectoroptionContainerStyle: {
    backgroundColor: "white",
  },
  modalselectorselectStyle: {
    width: "100%",
    height: "100%",
    alignItems: "flex-start",
    justifyContent: "center",
  },
  modalselectorsectionTextStyle: {
    fontSize: 18,
    fontFamily: "Inter-Bold",
  },
  modalselectorinitValueTextStyle: {
    color: "black",
    fontSize: 15,
    textTransform: "capitalize",
  },
  modalselectorcancelStyle: {
    backgroundColor: themes.colors.primary_light,
  },
  modalselectorcancelTextStyle: {
    color: "white",
    fontFamily: "Inter-Bold",
    fontSize: 18,
  },
  fullImageModalContainer: {
    flex: 1,
    width: "100%",
    height: "100%",
    margin: 0,
    padding: 0,
    marginVertical: Platform.OS == "ios" ? APPBAR_HEIGHT : 0,
    backgroundColor: "black",
  },
  fullImageModalCross: {
    backgroundColor: "black",
    borderRadius: 20,
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    top: Platform.OS == "ios" ? APPBAR_HEIGHT + 12 : 12,
    left: 12,
  },
  LinearGradientBox: {
    height: "100%",
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  InputLoc: {
    // borderWidth: 1,
    // borderColor: theme.colors.primary,
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 15,
    fontFamily: "Inter-Regular",
    backgroundColor: themes.colors.enableField,
  },
  ChargesTextloc: {
    fontSize: responsiveFontSize(1.8),
    fontFamily: "Inter-Regukar",
    lineHeight: 20,
    color: "#000",
  },
  BottomButton: {
    width: responsiveWidth(90),
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: themes.colors.primary,
    height: responsiveHeight(6),
    borderRadius: 10,
    alignSelf: "center",
    marginVertical: responsiveHeight(3),
  },
  buttonTextBottom: {
    color: "#fff",
    fontSize: responsiveFontSize(2),
    fontFamily: "Inter-Bold",
  },
  LinearGradient: {
    height: "100%",
    width: "100%",
    borderRadius: 6,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
  },
  Header: {
    paddingVertical: 10,
    width: "100%",
    flexDirection: "row",

    paddingHorizontal: 5,
    justifyContent: "space-between",
  },
  HeaderText: {
    color: themes.colors.textColor,
    fontSize: responsiveFontSize(3.3),
    marginLeft: 10,
    fontFamily: "Inter-Bold",
  },
  DropDownRightt: {
    // borderWidth: 0.5,
    // borderColor: theme.colors.placeholder,
    width: "100%",
    height: responsiveHeight(6),
    borderRadius: 6,
    justifyContent: "center",
    overflow: "hidden",
    marginTop: 5,
    backgroundColor: themes.colors.enableField,
  },
});

export default styles;
